#!/usr/bin/env sh

# https://docs.docker.com/docker-hub/builds/advanced/

if [ "${DOCKER_TAG}" = "native" ]; then
  contrib/native/build-in-container.sh
else
  # Build app via maven
  docker run --rm \
    -v "${PWD}":/work \
    -w /work \
    maven:3-openjdk-11 mvn -B -ntp clean package -DskipTests
fi

# Build container
docker build \
  --build-arg VERSION="$(echo "${DOCKER_TAG}" | sed -e 's/v//g')" \
  --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
  --build-arg VCS_REF="$(echo "${SOURCE_COMMIT}" | head -c 7)" \
  -f "${DOCKERFILE_PATH}" \
  -t "${IMAGE_NAME}" .
