#!/bin/bash


repo_path="$(git rev-parse --show-toplevel)"
current_branch="$(git rev-parse --abbrev-ref HEAD)"
origin_commit="$(git rev-parse --short "$(git merge-base master "$current_branch")")"
files_to_push="$(git diff --name-only "$origin_commit")"

# shellcheck source=../functions/libchartversion.sh
. "${repo_path}/githooks/functions/libchartversion.sh"

failed=0

for chart_name in $( cut -d'/' -f1,2 <<< "$files_to_push" | uniq ); do
    # Avoid checking chart version when modified dirs are not charts
    if [[ $chart_name = bitnami/* ]]; then
        printf '\033[01;33mValidating %s chart version:\n\033[0m' "$chart_name"
        if ! run_version_change_chart "$chart_name"; then
            failed=1
        fi
    fi
done

if [[ "$failed" = "1" ]]; then
    printf '\033[0;31m\U0001F6AB Chart version check failed. Not pushing\n\n\033[0m'
else
    printf '\033[0;32m\U00002705 Chart version check succeeded\n\n\033[0m'
fi

exit $failed
