#!/bin/bash

. ../functions/libhelmlint.sh

readonly current_branch="$(git rev-parse --abbrev-ref HEAD)"
readonly origin_commit="$(git rev-parse --short "$(git merge-base master "$current_branch")")"
readonly files_to_push="$(git diff --name-only "$origin_commit")"
failed=0

for chart_name in $( cut -d'/' -f1,2 <<< "$files_to_push" | uniq ); do
    # Avoid running 'helm lint|install' when modified dirs are not charts
    if [[ $chart_name = bitnami/* ]]; then
        printf '\033[01;33mValidating %s with helm lint:\n\033[0m' "$chart_name"
        chart_path="$(git rev-parse --show-toplevel)"/"$chart_name"
    fi
done

if [[ "$failed" = "1" ]]; then
    printf '\033[0;31m\U0001F6AB Helm lint failed. Not pushing\n\n\033[0m'
else
    printf '\033[0;32m\U00002705 Helm lint succeeded\n\n\033[0m'
fi

exit $failed
