#!/bin/bash

if git diff --name-only --cached origin/master | grep '/upstreamed/'; then
    printf '\n\U1F6AB Pull Request cancelled\n\nChanges detected in the "upstreamed" folder.\nPlease, implement them in the Helm Charts repository (https://github.com/helm/charts).\n'
fi

exit 0
