#!/bin/bash

readonly current_branch="$(git rev-parse --abbrev-ref HEAD)"
readonly origin_commit="$(git rev-parse --short "$(git merge-base master "$current_branch")")"
readonly files_to_push="$(git diff --name-only "$origin_commit")"
readonly repo_path="$(git rev-parse --show-toplevel)"

failed=0

render_and_yaml_lint() {
    local -r chart_path="${1:?missing_chart}"
    local -r path="${2:?missing_file}"
    local -r values="${3:?missing_values}"
    local -r display_chart_path=${1#"$repo_path/"}
    local -r display_values=${3#"$chart_path/"}
    local -r lint_rules="{extends: default, rules: {line-length: disable, trailing-spaces: disable, truthy: enable, document-start: disable, empty-lines: {max-end: 2} }}"
    printf '\033[0;34m- Running yamllint on %s/%s (values: %s)\n\033[0m' "$display_chart_path" "$path" "$display_values"

    if ! helm template --values "$values" "$chart_path" -x "$path" | yamllint -s -d "$lint_rules" -; then
        printf '\033[0;31m\\U0001F6AB (helm template --values %s %s -x %s | yamllint -s -d "%s" -) failed\n\n\033[0m' "$display_values" "$display_chart_path" "$path" "$lint_rules"
        false
    else
        printf '\033[0;32m\U00002705 %s/%s (values: %s)\n\n\033[0m' "$display_chart_path" "$path" "$display_values"
        true
    fi
}

yaml_lint_file() {
    local -r path="${1:?missing_file}"
    local -r lint_rules="{extends: default, rules: {line-length: disable, trailing-spaces: disable, truthy: enable, document-start: disable, empty-lines: {max-end: 2}}}"
    local -r display_path=${1#"$repo_path/"}
    printf '\033[0;34m- Running yamllint on %s\n' "$display_path"
    if ! yamllint -s -d "$lint_rules" "$path"; then
        printf '\033[0;31m\U0001F6AB yamllint -s -d "%s" %s failed\n\n\033[0m' "$lint_rules" "$display_path"
        false
    else
        printf '\033[0;32m\U00002705 %s\n\n\033[0m' "$display_path"
        true
    fi
}

check_yaml_lint() {
    if ! command -v yamllint > /dev/null 2>&1; then
        printf '\033[0;31m\U0001F6AB yamllint is not installed\033[0m'
        printf '  Installation for Linux'
        printf '    pip install --user yamllint'
        printf '  Installation for Mac OS'
        printf '    brew install yamllint'
        exit 1
    fi
}

for chart_name in $( cut -d'/' -f1,2 <<< "$files_to_push" | uniq ); do
    check_yaml_lint
    # Avoid running 'yamllint' when modified dirs are not charts
    if [[ $chart_name = bitnami/* ]]; then
        printf '\033[01;33mLinting yaml of %s:\n\033[0m' "$chart_name"
        chart_path="$repo_path"/"$chart_name"

        for yaml_file in "$chart_path"/values.yaml "$chart_path"/values-production.yaml "$chart_path"/requirements.yaml "$chart_path"/Chart.yaml "$chart_path"/ci/*; do
            if [[ -f "$yaml_file" ]] && ! yaml_lint_file "$yaml_file"; then
                failed=1
            fi
        done

        for values_file in "$chart_path"/values.yaml "$chart_path"/ci/*.yaml; do
            if [[ ! -f "$values_file" ]];then
                continue
            fi
            for yaml_file in "$chart_path"/templates/*.yaml; do
                path_basename=templates/$(basename "$yaml_file")
                if ! render_and_yaml_lint "$chart_path" "$path_basename" "$values_file"; then
                    failed=1
                fi
            done
        done
    fi
done

if [[ "$failed" = "1" ]]; then
    printf '\033[0;31m\U0001F6AB YAML lint failed. Not pushing\n\n\033[0m'
else
    printf '\033[0;32m\U00002705 YAML lint succeeded\n\n\033[0m'
fi

exit $failed
