{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.compactor.enabled .Values.compactor.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ default (include "thanos.compactor.fullname" $) .Values.compactor.httpRoute.name }}
  namespace: {{ include "common.names.namespace" . }}
  {{- $labels := include "common.tplvalues.merge" (dict "values" ( list .Values.compactor.httpRoute.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: compactor
  {{- if or .Values.compactor.httpRoute.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" ( list .Values.compactor.httpRoute.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.compactor.httpRoute.parentRefs }}
  parentRefs: {{- include "common.tplvalues.render" (dict "value" .Values.compactor.httpRoute.parentRefs "context" $) | nindent 4 }}
  {{- else }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway
      namespace: {{ include "common.names.namespace" . }}
  {{- end }}
  {{- if .Values.compactor.httpRoute.hostnames }}
  hostnames:
    {{- range .Values.compactor.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- else }}
  hostnames: [thanos.local]
  {{- end }}
  rules:
    - backendRefs:
        - name: {{ include "thanos.compactor.fullname" . }}
          port: {{ .Values.compactor.service.ports.http }}
      {{- if .Values.compactor.httpRoute.matches }}
      matches: {{- include "common.tplvalues.render" (dict "value" .Values.compactor.httpRoute.matches "context" $) | nindent 8 }}
      {{- else }}
      matches:
        - path:
            type: PathPrefix
            value: /
      {{- end }}
      {{- if .Values.compactor.httpRoute.filters }}
      filters: {{- include "common.tplvalues.render" (dict "value" .Values.compactor.httpRoute.filters "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.compactor.httpRoute.timeouts }}
      timeouts: {{- include "common.tplvalues.render" (dict "value" .Values.compactor.httpRoute.timeouts "context" $) | nindent 8 }}
      {{- end }}
    {{- if .Values.compactor.httpRoute.extraRules }}
    {{- include "common.tplvalues.render" (dict "value" .Values.compactor.httpRoute.extraRules "context" $) | nindent 4 }}
    {{- end }}
{{- end }}