{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.route }}
{{- range $name, $route := .Values.route }}
{{- if $route.enabled }}
apiVersion: {{ $route.apiVersion | default "gateway.networking.k8s.io/v1" }}
kind: {{ $route.kind | default "HTTPRoute" }}
metadata:
  name: {{ printf "%s-%s" (include "common.names.fullname" $) $name }}
  namespace: {{ include "common.names.namespace" $ | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $route.labels "context" $ ) | nindent 4 }}
  {{- if or $route.annotations $.Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list $route.annotations $.Values.commonAnnotations ) "context" $ ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- with $route.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $route.parentRefs }}
  parentRefs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - {{- with $route.matches }}
      matches:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.filters }}
      filters:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.sessionPersistence }}
      sessionPersistence:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $route.retry }}
      retry:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - kind: Service
          name: {{ include "common.names.fullname" $ }}
          port: {{ index $.Values.service.ports $route.backendService }}
---
{{- end }}
{{- end }}
{{- end }}
