{{- /*
Copyright Broadcom, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.receive.enabled .Values.receive.httpRoute.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ template "thanos.receive.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  {{- $labels := include "common.tplvalues.merge" (dict "values" ( list .Values.receive.httpRoute.labels .Values.commonLabels ) "context" . ) }}
  labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" .) | nindent 4 }}
    app.kubernetes.io/component: receive
  {{- if or .Values.receive.httpRoute.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" ( list .Values.receive.httpRoute.annotations .Values.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" .) | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
  {{- if .Values.receive.httpRoute.parentRefs }}
    {{- include "common.tplvalues.render" (dict "value" .Values.receive.httpRoute.parentRefs "context" .) | nindent 4 }}
  {{- else }}
    - name: gateway
      namespace: {{ include "common.names.namespace" . | quote }}
  {{- end }}
  hostnames: {{- include "common.tplvalues.render" (dict "value" .Values.receive.httpRoute.hostnames "context" .) | nindent 4 }}
  rules:
    - backendRefs:
        - name: {{ include "thanos.receive.fullname" . }}
          port: {{ .Values.receive.service.ports.http }}
          weight: 1
      {{- if .Values.receive.httpRoute.matches }}
      matches: {{- include "common.tplvalues.render" (dict "value" .Values.receive.httpRoute.matches "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.receive.httpRoute.filters }}
      filters: {{- include "common.tplvalues.render" (dict "value" .Values.receive.httpRoute.filters "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.receive.httpRoute.timeouts }}
      timeouts: {{- include "common.tplvalues.render" (dict "value" .Values.receive.httpRoute.timeouts "context" .) | nindent 8 }}
      {{- end }}
  {{- if .Values.receive.httpRoute.extraRules }}
    {{- include "common.tplvalues.render" (dict "value" .Values.receive.httpRoute.extraRules "context" .) | nindent 4 }}
  {{- end }}
{{- end }}